all: serverA servermain client

serverA: serverA.cpp
    g++ -o serverA serverA.cpp

servermain: servermain.cpp
    g++ -o servermain servermain.cpp

client: client.cpp
    g++ -o client client.cpp

clean:
    rm -f serverA servermain client
